apiVersion: v1
kind: Service
metadata:
  name: webook-live-redis
spec:
  selector:
    app: webook-live-redis
  ports:
    - protocol: TCP
#      作业
#      port: 6380
      port: 11479
#      Redis 默认端口
      targetPort: 6379
      nodePort: 30003
  type: NodePort