// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/geekbang/basic-go/webook/payment/ioc"
	"gitee.com/geekbang/basic-go/webook/payment/web"
	"gitee.com/geekbang/basic-go/webook/pkg/wego"
)

// Injectors from wire.go:

func InitApp() *wego.App {
	wechatConfig := ioc.InitWechatConfig()
	handler := ioc.InitWechatNotifyHandler(wechatConfig)
	loggerV1 := ioc.InitLogger()
	wechatHandler := web.NewWechatHandler(handler, loggerV1)
	server := ioc.InitGinServer(wechatHandler)
	app := &wego.App{
		WebServer: server,
	}
	return app
}
