// Code generated by MockGen. DO NOT EDIT.
// Source: ./cron_job.go
//
// Generated by this command:
//
//	mockgen -source=./cron_job.go -package=svcmocks -destination=mocks/cron_job.mock.go CronJobService
//
// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	domain "gitee.com/geekbang/basic-go/webook/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCronJobService is a mock of CronJobService interface.
type MockCronJobService struct {
	ctrl     *gomock.Controller
	recorder *MockCronJobServiceMockRecorder
}

// MockCronJobServiceMockRecorder is the mock recorder for MockCronJobService.
type MockCronJobServiceMockRecorder struct {
	mock *MockCronJobService
}

// NewMockCronJobService creates a new mock instance.
func NewMockCronJobService(ctrl *gomock.Controller) *MockCronJobService {
	mock := &MockCronJobService{ctrl: ctrl}
	mock.recorder = &MockCronJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCronJobService) EXPECT() *MockCronJobServiceMockRecorder {
	return m.recorder
}

// Preempt mocks base method.
func (m *MockCronJobService) Preempt(ctx context.Context) (domain.CronJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preempt", ctx)
	ret0, _ := ret[0].(domain.CronJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preempt indicates an expected call of Preempt.
func (mr *MockCronJobServiceMockRecorder) Preempt(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preempt", reflect.TypeOf((*MockCronJobService)(nil).Preempt), ctx)
}

// ResetNextTime mocks base method.
func (m *MockCronJobService) ResetNextTime(ctx context.Context, job domain.CronJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetNextTime", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetNextTime indicates an expected call of ResetNextTime.
func (mr *MockCronJobServiceMockRecorder) ResetNextTime(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetNextTime", reflect.TypeOf((*MockCronJobService)(nil).ResetNextTime), ctx, job)
}
