// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/geekbang/basic-go/webook/internal/sms/grpc"
	ioc2 "gitee.com/geekbang/basic-go/webook/internal/sms/ioc"
)

// Injectors from wire.go:

func Init() *App {
	service := ioc2.InitSmsTencentService()
	smsServiceServer := grpc.NewSmsServiceServer(service)
	server := ioc2.InitGRPCxServer(smsServiceServer)
	app := &App{
		server: server,
	}
	return app
}
