// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gitee.com/geekbang/basic-go/webook/pkg/wego"
	"gitee.com/geekbang/basic-go/webook/sms/grpc"
	"gitee.com/geekbang/basic-go/webook/sms/ioc"
)

// Injectors from wire.go:

func Init() *wego.App {
	service := ioc.InitSmsTencentService()
	smsServiceServer := grpc.NewSmsServiceServer(service)
	client := ioc.InitEtcdClient()
	loggerV1 := ioc.InitLogger()
	server := ioc.InitGRPCxServer(smsServiceServer, client, loggerV1)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}
